import Head from "next/head";
import Link from "next/link";

import {
  Category,
  Container,
  SectionTitle,
  Item,
  Icon,
} from "../../styles/catalog";

export const getStaticProps = async () => {
  const url = "http://127.0.0.1:8000/category/all";
  const res = await fetch(url);
  const data = await res.json();
  return {
    props: { categories: data },
  };
};

const CategoryList = ({ categories }) => {
  return (
    <>
      <Head>
        <title>Categories - Decolight</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SectionTitle>Категории Декора</SectionTitle>
      <Container>
        {categories.map((e, inx) => (
          <Link
            href={`/catalog/category/${e.id}`}
            passHref
            key={inx}
            // onClick={() => setCurrent(e.name)}
          >
            <Category.Box>
              <div style={{ position: "relative" }}>
                <Item.Picture src={e.image} width={250} height={250} />
              </div>
              <Category.Title>{e.name}</Category.Title>
              <Category.Description>
                <div>
                  <Icon.Info />
                </div>
                <div>{e.description}</div>
              </Category.Description>
            </Category.Box>
          </Link>
        ))}
      </Container>
    </>
  );
};

export default CategoryList;
