import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";

import { Provider } from "react-redux";
import { store } from "../../modules/constructor/store/store";

import * as styled from "../../styles/constructor";
import { Welcome } from "../../styles/index";

import dynamic from "next/dynamic";
// dynamically import these components - to improve perfomance
const Window = dynamic(() => import("../../modules/constructor/window/Window"));
const Door = dynamic(() => import("../../modules/constructor/door/Door"));

const Constructor = () => {
  const router = useRouter();
  const element = router.query?.element;
  return (
    <>
      <Provider store={store}>
        <Head>
          <title>Конструктор декора - Decolight</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <styled.ConstructorMenu.Container fullSize={!element ? 1 : 0}>
          {!element && <Welcome.Image src="images/main-profile.png" alt="" />}
          <styled.ConstructorMenu.Title>
            Выберите элемент фасада
          </styled.ConstructorMenu.Title>
          <styled.ConstructorMenu.ItemLinkContainer>
            <Link href="/constructor/window" passHref>
              <styled.ConstructorMenu.ItemLink>
                Окно
              </styled.ConstructorMenu.ItemLink>
            </Link>
            <Link href="/constructor/door" passHref>
              <styled.ConstructorMenu.ItemLink>
                Дверь
              </styled.ConstructorMenu.ItemLink>
            </Link>
          </styled.ConstructorMenu.ItemLinkContainer>
        </styled.ConstructorMenu.Container>
        {element && (
          <styled.ConstructorContainer>
            <styled.SceneContainer>
              {element[0] === "window" ? <Window /> : <Door />}
            </styled.SceneContainer>
          </styled.ConstructorContainer>
        )}
      </Provider>
    </>
  );
};

export default Constructor;
