import Head from "next/head";
import Link from "next/link";

import { gql } from "@apollo/client";
import client from "../../apollo-client";

import {
  Category,
  Container,
  ContentContainer,
  SectionTitle,
  Item,
  Icon,
} from "../../styles/catalog";

export const getStaticProps = async () => {
  const { data } = await client.query({
    query: gql`
      query CategoryList {
        categories {
          id
          name
          description
        }
      }
    `,
  });
  return {
    props: { categories: data.categories },
  };
};

const CategoryList = ({ categories }) => {
  return (
    <>
      <Head>
        <title>Categories - Decolight</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <SectionTitle>Категории Декора</SectionTitle>
        <ContentContainer>
          {categories.map((e, inx) => (
            <Link href={`/catalog/category/${e.id}`} passHref key={inx}>
              <Category.Box>
                <div style={{ position: "relative" }}>
                  <Item.Picture
                    src={`/categories/image/${e.id}.png`}
                    width={250}
                    height={250}
                  />
                </div>
                <Category.Title>{e.name}</Category.Title>
                <Category.Description>
                  <div>
                    <Icon.Info />
                  </div>
                  <div>{e.description}</div>
                </Category.Description>
              </Category.Box>
            </Link>
          ))}
        </ContentContainer>
      </Container>
    </>
  );
};

export default CategoryList;
