import { gql } from "@apollo/client";
import client from "../../../apollo-client";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";

import {
  Container,
  ContentContainer,
  SectionTitle,
  Item,
  BackBtn,
  Icon,
} from "../../../styles/catalog";

import dynamic from "next/dynamic";
import DecorItemInterface from "../../../api/DecorItemInterface";
const ItemModal = dynamic(() => import("../../../modules/catalog/ItemModal"));
const ItemDetails = dynamic(() =>
  import("../../../modules/catalog/ItemDetails")
);

export const getStaticPaths = async () => {
  const { data } : {data: {categories: {id: number}[]}} = await client.query({
    query: gql`
      query CategoryList {
        categories {
          id
        }
      }
    `,
  });
  const paths = data.categories.map((e : {id: number}) => ({
    params: {
      id: e.id.toString(),
    },
  }));

  return {
    paths,
    fallback: false,
  };
};


interface StaticPropsFetchI {
  data: {
    categories_by_pk: {
      name: string;
      items: DecorItemInterface[]
    }
  }
}
type StatisPropsType = StaticPropsFetchI | undefined;
export const getStaticProps = async ({ params } : {params: {id: string}}) => {
  const res: StatisPropsType = await client.query({
    query: gql`
      query ItemsByCategory${params.id} {
        categories_by_pkk(id: ${params.id}) {
          name
          items {
            id
            name
            height
            width
            price
          }
        }
      }
    `,
  });

  const category: string | undefined = res?.data?.categories_by_pk.name;
  const items: DecorItemInterface[] | undefined = res?.data?.categories_by_pk.items;

  return {
    props: {
      category,
      items,
    },
  };
};

interface CategoryDetailProps {
  category: string;
  items: DecorItemInterface[]
}

const CategoryDetail = ({ category, items } : CategoryDetailProps) => {
  // modal
  const [modal, setModal] = useState<DecorItemInterface | undefined>(undefined);

  const closeModal = () => setModal(undefined);

  return (
    <>
      <Head>
        <title>{category} - Категории - Decolight</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <SectionTitle>{category}</SectionTitle>
        <Link href="/catalog" passHref>
          <BackBtn>
            <Icon.Back /> Обратно в категории
          </BackBtn>
        </Link>
        <ContentContainer>
          {items.map((e, inx) => (
            <Item.Box key={inx} onClick={() => setModal(e)}>
              <Item.Picture
                src={`/items/image/${e.id}.jpg`}
                width={250}
                height={150}
              />
              <ItemDetails elem={e} />
            </Item.Box>
          ))}
          <ItemModal item={modal} close={closeModal} />
        </ContentContainer>
      </Container>
    </>
  );
};

export default CategoryDetail;
