"""Image

Revision ID: a3fb6e1c05f7
Revises: 765c3e72a009
Create Date: 2022-01-08 21:50:09.341671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fb6e1c05f7'
down_revision = '765c3e72a009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image')
    # ### end Alembic commands ###
