import Head from "next/head";

import {
  Container,
  Title,
  Text,
  Icon,
  ContactElem,
  ContentBox,
} from "../../styles/contacts";

import { ApolloProvider } from "@apollo/client";
import client from "../../apollo-client";
import dynamic from "next/dynamic";
const Form = dynamic(() => import("../../modules/contacts/Form"));

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Contacts - Decolight</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <Title>НАШИ КОНТАКТЫ</Title>
        <ContentBox>
          <ApolloProvider client={client}>
            <Form />
          </ApolloProvider>
          <ContactElem.Box>
            <Text>
              Если у вас есть вопросы или идеи, которыми вы бы хотели
              поделиться, отправьте сообщение. Для более подробной информации Вы
              можете связаться с нами по телефону, указанному ниже.
            </Text>
            <ContactElem.Item>
              <Icon.Phone />
              +7-911-756-5366
            </ContactElem.Item>
            <ContactElem.Item>
              <Icon.Map /> ул. Лесная д. 3в
            </ContactElem.Item>
            <ContactElem.Item>
              <Icon.Mail />
              info@decolight.com
            </ContactElem.Item>
          </ContactElem.Box>
        </ContentBox>
      </Container>
    </>
  );
};

export default Contacts;
