import Head from "next/head";

import {
  Container,
  Title,
  Text,
  Icon,
  ContactElem,
  ContentBox,
  FormElem,
} from "../../styles/contacts";
import Spinner from "../../modules/common/Spinner";

import { gql, useMutation } from "@apollo/client";
import client from "../../apollo-client";

const SUBMIT_CONTACT = gql`
  mutation submitContact(
    $email: String
    $message: String
    $name: String
    $phone: numeric
  ) {
    insert_submit_one(
      object: { email: $email, message: $message, name: $name, phone: $phone }
    ) {
      id
    }
  }
`;

const Contacts = () => {
  const [sendForm, { data, loading, error }] = useMutation(SUBMIT_CONTACT, {
    client,
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    const { email, message, phone, name } = [...e.target].reduce(
      (obj, curr) => (curr.id ? { ...obj, [curr.id]: curr.value } : { ...obj }),
      {}
    );
    sendForm({
      variables: {
        email,
        message,
        phone,
        name,
      },
    });
  };
  return (
    <>
      <Head>
        <title>Contacts - Decolight</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <Title>НАШИ КОНТАКТЫ</Title>
        <ContentBox>
          <FormElem.Container>
            <FormElem.Title>Остались вопросы?</FormElem.Title>
            <FormElem.Text>
              Оставьте свои контактные данные и мы обязательно свяжемся для
              более подробного обсуждения вашего проекта.
            </FormElem.Text>
            {error && !loading && (
              <FormElem.Error>
                Произошла ошибка. Повторите отправку данных.
              </FormElem.Error>
            )}
            {data && !error ? (
              <FormElem.Success>
                <Icon.Done /> Сообщение отправлено
              </FormElem.Success>
            ) : loading ? (
              <FormElem.Success>
                <Spinner />
              </FormElem.Success>
            ) : (
              <FormElem.Form onSubmit={handleSubmit}>
                <FormElem.Input
                  placeholder="Имя"
                  name="name"
                  id="name"
                  type="text"
                />
                <FormElem.Input
                  placeholder="Телефон"
                  name="phone"
                  id="phone"
                  type="text"
                />
                <FormElem.Input
                  placeholder="Электронная почта"
                  name="email"
                  id="email"
                  type="text"
                />
                <FormElem.TextArea
                  placeholder="Сообщение"
                  name="message"
                  id="message"
                  type="text"
                />
                <FormElem.SumbitBtn type="submit" value="ОТПРАВИТЬ" />
              </FormElem.Form>
            )}
          </FormElem.Container>

          <ContactElem.Box>
            <Text>
              Если у вас есть вопросы или идеи, которыми вы бы хотели
              поделиться, отправьте сообщение. Для более подробной информации Вы
              можете связаться с нами по телефону, указанному ниже.
            </Text>
            <ContactElem.Item>
              <Icon.Phone />
              +7-911-756-5366
            </ContactElem.Item>
            <ContactElem.Item>
              <Icon.Map /> ул. Лесная д. 3в
            </ContactElem.Item>
            <ContactElem.Item>
              <Icon.Mail />
              info@decolight.com
            </ContactElem.Item>
          </ContactElem.Box>
        </ContentBox>
      </Container>
    </>
  );
};

export default Contacts;
